main: com.cavetale.blockclip.BlockClipPlugin
name: BlockClip

version: 0.1
api-version: 1.17

description: Simple Schematics Plugin
author: StarTux
website: https://cavetale.com

depend: []
softdepend: [WorldEdit]

commands:

  blockclip:
    aliases: [bclip]
    description: BlockClip user interface
    permission: blockclip.blockclip
    usage: |-
      /bclip copy - Copy to clipboard
      /bclip paste - Paste clipboard
      /bclip show - Preview clipboard
      /blcip list [pattern] - List clip files
      /bclip save <path> - Save to file
      /bclip load <path> - Load file
      /bclip meta <key> <value> - Set clipboard meta
      /bclip info - Clipboard info

permissions:

  blockclip.blockclip:
    description: Use /blockclip
